module.exports = {
    DEPOSIT: 'DEPOSIT',
    DEPOSIT_FEE: 'DEPOSIT_FEE',
    WITHDRAW: 'WITHDRAW',
    WITHDRAW_FEE: 'WITHDRAW_FEE',
    TRANSFER_INTERNAL: 'TRANSFER_INTERNAL',
    TRANSFER_INTERNAL_FEE: 'TRANSFER_INTERNAL_FEE',
    SPOT_LOCK: 'SPOT_LOCK',
    SPOT_PLACE_ORDER: 'SPOT_PLACE_ORDER',
    SPOT_MATCH_ORDER: 'SPOT_MATCH_ORDER',
    SPOT_CLOSE_ORDER: 'SPOT_CLOSE_ORDER',
    SPOT_FEE: 'SPOT_FEE',
    SPOT_COMMISSION_BROKER: 'SPOT_COMMISSION_BROKER',
    SPOT_COMMISSION_BROKER_KYC: 'SPOT_COMMISSION_BROKER_KYC',
    SWAP_PLACE_ORDER: 'SWAP_PLACE_ORDER',
    SWAP_FEE: 'SWAP_FEE',
    STAKE_REWARD: 'STAKE_REWARD'
}
