'use strict'

const Model = use('Model')

class TransactionHistory extends Model {
}

module.exports = TransactionHistory

TransactionHistory.Category = {
    ROLLBACK_WALLET: 0,
    ORDER_REQUIRED_MARGIN: 1,
    ORDER_CLOSE_ORDER_MARGIN_BACK: 2,
    ORDER_CLOSE_PROFIT: 3,
    DEPOSIT: 4,
    WITHDRAW: 5,
    ORDER_MODIFY_NAC_BET: 6,
    ORDER_FEE_REFER: 7,

    MONEY_REVERSE_MULTI_CLOSE: 20,
    ORDER_MULTI_CLOSE_REVERSED: 21,

    ORDER_WITHDRAW_NLF_REVENUE: 26,

    EXCHANGE_PLACE_SELL: 30,
    EXCHANGE_CLOSE_SELL: 31,
    EXCHANGE_RETURN_NAC: 32,

    COINBASE_DEPOSIT_BTC: 36,
    TRANSFER_NAC: 43,
    TRANSFER_WALLET_TOKEN: 44,
    BUY_ETH_FROM_ROOT: 45,

    TRANSFER_ON_RESET: 50,

    WITHDRAW_REFER_NAC_MONEY: 60,

    CONVERT_TOKEN_TO_ETH_DEDUCTION: 70,
    CONVERT_TOKEN_TO_ETH_RECEIVED: 71,


    FEE_CONVERT_TOKEN: 90,
    FEE_WITHDRAW: 91,
    FEE_DEPOSIT: 92,

    DEPOSIT_REBATE: 95,

    CAMPAIGN_BONUS_FREE_TURN: 99,
    CAMPAIGN_ON_TURN: 100,
    BUY_TURN: 101,
    CAMPAIGN_REWARD: 102,
    CAMPAIGN_BONUS_TURN: 103,
    CAMPAIGN_TURN_ROLLBACK: 104,

    // NAMI EXCHANGE
    EXCHANGE_LOCK_CURRENCY: 130,
    EXCHANGE_MATCH_ORDER: 131,
    EXCHANGE_CLOSE_ORDER: 132,
    EXCHANGE_FEE: 133,

    CHANGE_BALANCE_ROOT_WALLET: 990,
    CHANGE_BALANCE_BURN_WALLET: 991,
    CHANGE_BALANCE_CUSTOMER_WALLET: 992,
    CHANGE_BALANCE_EXCHANGE_WALLET: 993,
    CHANGE_BALANCE_EXCHANGE_FEE_WALLET: 994,

    // Refer
    COMMON_REFER_LV_1: 402,
    COMMON_REFER_LV_2: 403,

    BUY_BACK: 410,
    BATCH_DEPOSIT: 415,

    // Buy back BNB
    BUY_BACK_LOAN_FEE: 500,
    BUY_BACK_REGISTER_SELL: 501,
    BUY_BACK_PROFIT_USE_LOAN: 502,
    BUY_BACK_PROFIT_USE_MAIN: 503,

    BUY_BACK_REGISTER_HOLD: 504,

    // Future 600-700
    FUTURE_PLACE_ORDER_FEE: 600,
    FUTURE_PLACE_ORDER_MARGIN: 601,
    FUTURE_CLOSE_ORDER_PROFIT: 602,
    FUTURE_SWAP: 603,
    FUTURE_REFERRAL_COMMISION: 604,
    FUTURE_VNDC_FEE_PROMOTE: 605,

    FUTURE_COPY_TRADE_PROFIT_TO_MASTER: 662,
    FUTURE_COPY_TRADE_PROFIT_TO_NAMI: 663,

    // Air drop
    AIR_DROP_1508: 1000
}

TransactionHistory.Status = {
    NONE: 0,

    // Withdraw
    WITHDRAW_WAITING: 1,
    WITHDRAW_DONE: 2,
    WITHDRAW_REJECTED: 3,
    WITHDRAW_TRANSFER_BACK: 4,
    WITHDRAW_TX_PENDING: 5,
    WITHDRAW_ETH_WAITING: 11,
    WITHDRAW_ETH_DONE: 12,
    WITHDRAW_ETH_REJECTED: 13,
    WITHDRAW_ETH_TRANSFER_BACK: 14,
    WITHDRAW_ETH_TX_PENDING: 15
}
